#ifndef ERGODOX_EZ_CONFIG_H
#define ERGODOX_EZ_CONFIG_H

#include QMK_KEYBOARD_CONFIG_H

#undef DEBOUNCE
#define DEBOUNCE    10

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 3000

#endif
#define ONESHOT_TIMEOUT 3000
#define TAPPING_TERM 200
#define PREVENT_STUCK_MODIFIERS
#define FORCE_NKRO
#define LEADER_TIMEOUT 1000

